name: condutta_med
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  brasil_fields: ^1.15.0
  flutter_flavorizr: ^2.2.1
  firebase_core: ^3.4.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Instrument Sans
      fonts:
        - asset: assets/fonts/InstrumentSans-Regular.ttf
        - asset: assets/fonts/InstrumentSans-Bold.ttf
          weight: 700

flavorizr:
  ide: "vscode"
  flavors:
    conduttaMed:
      app:
        name: "ConduttaMed"
      android: "com.business.conduttaMed"
      ios: "com.business.conduttaMed"
